# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69b7041823c5f100274edffa86b534be212d901e5d4b21eb2f2bbdf16044fa22469676994fa3e9705db601fc9797728ec4d12f7b78830fa0e2dfd97bbe22aa29
  s3_bucket_name: crudcrud
  aws_access_key_id: AKIAI5X4ODIQ3JN7WZYQ
  aws_secret_access_key: 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


test:
  secret_key_base: aef7c4593cc9fc64b9c3c876b0f6d1f905e39f1d2285b1383ee423e9604af49926afa233f1a4a575c1cb2cba9f5308629428320eff1140d515d5bb5bdbe5b0d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # This will get supplied by Heroku and this file won't 
  # be uploaded anyway so this line isn't actually necessary
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  # Note: You'll need to use the heroku_secrets gem to
  # port these over to Heroku as environment variables
  # of the same name.
  s3_bucket_name: crudcrud
  aws_access_key_id: AKIAI5X4ODIQ3JN7WZYQ
  aws_secret_access_key: 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
